services:
  causal-orders-app:
    image: orders:latest
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://causal-orders-db:5432/ordersdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://o11y-otel-collector:4318
    depends_on:
      causal-orders-db:
        condition: service_healthy
    networks:
      causal-net:
        ipv4_address: 172.20.0.50
  causal-orders-db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=ordersdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - causal-orders-db-data:/var/lib/postgresql
    networks:
      causal-net:
        ipv4_address: 172.20.0.51

networks:
  causal-net:
    external: true
    name: causal_causal-net

volumes:
  causal-orders-db-data:
