include:
  - identity/docker-compose.yml
  - product/docker-compose.yml

services:
  gateway:
    image: caddy:latest
    ports:
      - "8090:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
