include:
  - identity/docker-compose.yml
  - product/docker-compose.yml
  - cart/docker-compose.yml
  - inventory/docker-compose.yml
  - profile/docker-compose.yml

services:
  causal-gateway:
    image: caddy:latest
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://o11y-otel-collector:4318
      - OTEL_SERVICE_NAME=causal-gateway
    networks:
      causal-net:
        ipv4_address: 172.20.0.2

networks:
  causal-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
