services:
  causal-inventory-app:
    image: inventory:latest
    depends_on:
      causal-inventory-db:
        condition: service_healthy
    networks:
      causal-net:
        ipv4_address: 172.20.0.40
  causal-inventory-db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=inventorydb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - causal-inventory-db-data:/var/lib/postgresql
    networks:
      causal-net:
        ipv4_address: 172.20.0.41

networks:
  causal-net:
    external: true
    name: causal_causal-net

volumes:
  causal-inventory-db-data:
