services:
  causal-cart-app:
    image: cart:latest
    depends_on:
      causal-cart-db:
        condition: service_healthy
    networks:
      causal-net:
        ipv4_address: 172.20.0.30
  causal-cart-db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=cartdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - causal-cart-db-data:/var/lib/postgresql
    networks:
      causal-net:
        ipv4_address: 172.20.0.31

networks:
  causal-net:
    external: true
    name: causal_causal-net

volumes:
  causal-cart-db-data:
