services:
  causal-cart-app:
    image: cart:latest
    env_file:
      - ../.env
    depends_on:
      causal-cart-db:
        condition: service_healthy
      causal-kafka:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/8080"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s
    networks:
      causal-net:
        ipv4_address: 172.20.0.30
  causal-cart-db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=cartdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - causal-cart-db-data:/var/lib/postgresql
    networks:
      causal-net:
        ipv4_address: 172.20.0.31

volumes:
  causal-cart-db-data:
