receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

exporters:
  prometheusremotewrite:
    endpoint: http://o11y-prometheus:9090/api/v1/write

  otlp_grpc/tempo:
    endpoint: http://o11y-tempo:4317
    tls:
      insecure: true

  otlp_http/loki:
    endpoint: http://o11y-loki:3100/otlp

processors:
  batch:
    timeout: 2s
    send_batch_size: 128

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheusremotewrite]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp_grpc/tempo]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp_http/loki]
