spring.application.name=identity

# Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/userdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

# Flyway Configuration
spring.flyway.enabled=true
logging.level.org.flywaydb=DEBUG

# JPA / Hibernate properties
# We use 'validate' so Hibernate checks if the schema matches the entities but doesn't modify it.
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.private-key-path=${JWT_PRIVATE_KEY_PATH:../keys/private.pem}
jwt.public-key-path=${JWT_PUBLIC_KEY_PATH:../keys/public.pem}
# 5 minutes in milliseconds
jwt.expiration=300000
# 7 days in milliseconds
jwt.refreshExpiration=604800000