CREATE TABLE order_addresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label VARCHAR(100),
    line1 VARCHAR(255) NOT NULL,
    line2 VARCHAR(255),
    city VARCHAR(100) NOT NULL,
    state VARCHAR(100) NOT NULL,
    country VARCHAR(100) NOT NULL,
    pincode VARCHAR(20) NOT NULL,
    phone_number VARCHAR(50),
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

ALTER TABLE orders
    DROP COLUMN IF EXISTS address_label,
    DROP COLUMN IF EXISTS address_line1,
    DROP COLUMN IF EXISTS address_line2,
    DROP COLUMN IF EXISTS address_city,
    DROP COLUMN IF EXISTS address_state,
    DROP COLUMN IF EXISTS address_country,
    DROP COLUMN IF EXISTS address_pincode,
    DROP COLUMN IF EXISTS address_phone_number,
    ADD COLUMN shipping_address_id BIGINT REFERENCES order_addresses(id),
    ADD COLUMN billing_address_id BIGINT REFERENCES order_addresses(id);
