services:
  id-app:
    image: id-service:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.id-service.rule=PathPrefix(`/auth/login`) || PathPrefix(`/auth/register`) || PathPrefix(`/auth/refresh`) || PathPrefix(`/auth/logout`) || PathPrefix(`/auth/me`)"
      - "traefik.http.routers.id-service.entrypoints=web"
      - "traefik.http.routers.id-service.middlewares=cors"
      - "traefik.http.services.id-service.loadbalancer.server.port=8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://id-db:5432/userdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      id-db:
        condition: service_healthy
  id-db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=userdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - id-db-data:/var/lib/postgresql

volumes:
  id-db-data: